
[api]
port = 54321
schemas = ["public", "auth", "storage", "realtime"]
extra_search_path = ["public", "auth"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_captcha_enabled = false
security_captcha_provider = "hcaptcha"

[studio]
enabled = true
port = 54323
