// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpiflhanqpnjctgfpfxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaWZsaGFucXBuamN0Z2ZwZnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzY1NzQsImV4cCI6MjA2NDcxMjU3NH0.Vl09YZHZg6O7PZpne0kTQJm2FLW-JlVzhS28YTAetds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);